### PR TITLE
UI view and configuration file

### PR DESCRIPTION
**Pull request by msamgan**
image

I added a UI view for the same table, which is available in the terminal.
Also, now we have the configuration available now. 

Improved UI, inspired by @mrPunyapal

### CODE REVIEW

**Comment by tbleckert** [comment]
Would be nice with a guard here, similar to Horizon and other dashboards in the ecosystem.

```php
Gate::define('viewPan', fn ($user) =>  $user->isAdmin());
```

This would maybe make `pan.ui.path_middlewares` and `pan.ui.enabled` obsolete. Great work either way, would love to see this implemented.

**Comment by msamgan** [comment]
> Would be nice with a guard here, similar to Horizon and other dashboards in the ecosystem.
> 
> ```
> Gate::define('viewPan', fn ($user) =>  $user->isAdmin());
> ```
> 
> This would maybe make `pan.ui.path_middlewares` and `pan.ui.enabled` obsolete. Great work either way, would love to see this implemented.

Thanks for the input @tbleckert .
Let's hear it from @nunomaduro  and the core team, and will make adjustments according to that. 
Lets hear what they have to say.

**Comment by msamgan** [comment]
I saw the configuration update.
closing this to update it once the configuration update is released.

**Comment by MrPunyapal** [comment]
You were able to make it draft 👀

**Pull request closed without merging**
